name: build

on: push

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "/home/runner/.pyenv/bin" >> $GITHUB_PATH
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up grading environment
      run: |
        curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        pyenv install 3.6.3
        echo "eval '$(pyenv init -)'" >> ~/.bashrc
        eval "$(pyenv virtualenv-init -)" >> ~/.bashrc
        source ~/.bashrc
        pyenv global 3.6.3
        pip install --upgrade pip
        pip install pipenv
        pip install coverage
    - name: Lint with flake8
      run: |
        pipenv install --dev
        pipenv run flake8 termfrequency
      #continue-on-error: true
    - name: Lint with pylint
      run: |
        pipenv run pylint termfrequency
      #continue-on-error: true
    - name: Check pydocstyle
      run: |
        pipenv run pydocstyle
    - name: Run testing
      run: |
        pipenv run pytest
      #continue-on-error: true
    - name: Check practical
      run: |
        gradle grade
        #continue-on-error: true
      if: always()
      env:
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1
